# Regresión lineal en Python
## El paquete scikit-learn para regresion lineal y la seleccion de rasgos

In [3]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
import pandas as pd
import numpy as np

In [4]:
data = pd.read_csv("../datasets/ads/Advertising.csv")

In [5]:
feature_cols = ["TV","Radio","Newspaper"]

In [6]:
x = data[feature_cols]
y = data["Sales"]

In [7]:
estimator = SVR(kernel="linear")
selector = RFE(estimator,2,step=1)
selector = selector.fit(x,y)

Cuales son las variables seleccionadas para el modelo
TV -> true
Radio-> true
Newspaper -> false

In [9]:
selector.support_

array([ True,  True, False])

In [10]:
selector.ranking_

array([1, 1, 2])

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
x_pred = x[["TV","Radio"]]

In [13]:
lm = LinearRegression()
lm.fit(x_pred,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [14]:
lm.intercept_

2.9210999124051362

In [15]:
lm.coef_

array([0.04575482, 0.18799423])

In [16]:
lm.score(x_pred,y)

0.8971942610828956