In [3]:
import numpy as np

In [6]:
data = np.random.random(90).reshape(30,3)
data

array([[0.35577718, 0.01670724, 0.82460715],
       [0.79953475, 0.03912937, 0.52758077],
       [0.04843915, 0.71893556, 0.14246519],
       [0.97500089, 0.48692277, 0.67382835],
       [0.66532632, 0.12145159, 0.8233258 ],
       [0.38007678, 0.86445903, 0.142633  ],
       [0.31529624, 0.15795774, 0.38787929],
       [0.49672972, 0.31956594, 0.23911866],
       [0.74763507, 0.13804417, 0.87083958],
       [0.92878687, 0.18675543, 0.2248408 ],
       [0.38464889, 0.79919067, 0.2429166 ],
       [0.77281782, 0.96426488, 0.36626917],
       [0.9079907 , 0.31676468, 0.70445404],
       [0.15192497, 0.2752042 , 0.49611415],
       [0.12121641, 0.18613989, 0.12621475],
       [0.30887247, 0.30750799, 0.97280492],
       [0.83975005, 0.42890859, 0.73415349],
       [0.50503297, 0.12870632, 0.6236026 ],
       [0.73362029, 0.07805683, 0.34335886],
       [0.38652749, 0.90890339, 0.59717718],
       [0.78109097, 0.90393208, 0.12060154],
       [0.83850353, 0.31116107, 0.82123082],
       [0.

In [7]:
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1],data[c2]])
clust_centers

array([[0.30887247, 0.30750799, 0.97280492],
       [0.16877913, 0.27671319, 0.42185457]])

In [9]:
from scipy.cluster.vq import vq

In [10]:
vq(data,clust_centers)

(array([0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
        0, 0, 0, 1, 0, 1, 1, 0]),
 array([0.32973884, 0.68225856, 0.53675019, 0.75186682, 0.42897592,
        0.68414659, 0.19163622, 0.37786289, 0.48127698, 0.79026489,
        0.59295976, 0.91688593, 0.65653677, 0.07616315, 0.31283964,
        0.        , 0.59457851, 0.41913595, 0.60388034, 0.69124295,
        0.92686716, 0.55090571, 0.24976931, 0.46272166, 0.61480739,
        0.        , 1.03703218, 0.31405617, 0.7453984 , 0.70928034]))

In [11]:
from scipy.cluster.vq import kmeans

In [12]:
kmeans(data,clust_centers)

(array([[0.68908134, 0.29998081, 0.72538627],
        [0.41950927, 0.62266797, 0.30582625]]), 0.3805717641981321)

In [13]:
kmeans(data,2)

(array([[0.41950927, 0.62266797, 0.30582625],
        [0.68908134, 0.29998081, 0.72538627]]), 0.3805717641981321)